### PR TITLE
fix: fix DWARF file indices in the `debug_line` section

### LINKED ISSUE #4939: Incorrect Line Numbers When Parsing `.debug_line` with `gimli`
I attempted to use the `gimli` library to parse the `.debug_line` section of a WebAssembly (Wasm) file that includes debug information. The Wasm file was written in Motoko and compiled using `moc`. However, `gimli` produced incorrect line numbers during parsing.  

My implementation is nearly identical to the example provided in the `gimli` library, yet it still fails to retrieve the correct line numbers. To further investigate, I tested my implementation on Wasm files compiled with `cargo`, and the results were entirely correct. 

Image

Image

### PR DESCRIPTION
**Pull request by Kamirus**
Instructions how to run it and how I've verified it when testing the motoko_debugger:
- Switch to this branch in the motoko repo and execute `nix develop` (this will put the locally build `moc` in the PATH)
- Have the `motoko-core` repo checkout on the branch `kamil/experiment-debugger-manual-test` next to this repo, go there: `cd ../motoko-core` (here we have the test files we would like to debug)
- Clone and [build](https://github.com/scalebit/motoko_debugger?tab=readme-ov-file#build-instructions) the `motoko_debugger`
- `make -C ../motoko/src moc && moc $(mops sources) -o MoDe.wasm -g --legacy-persistence test/List.test.mo && ~/motoko_debugger/target/release/debugger MoDe.wasm`. It builds the `moc` compiler and then compiles the problematic List test file, and finally runs the debugger on it. It should start and run to the end without problems now.

The debug line section in DWARF can be verified with
- `make -C ../motoko/src moc && moc $(mops sources) -o MoDe.wasm -g --legacy-persistence test/List.test.mo && llvm-dwarfdump --debug-line MoDe.wasm > out`
- open the out file in the editor and look for the `File` column, the file indices should not exceed the number of files

The only relevant changes are in the [src/wasm-exts/customModuleEncode.ml](https://github.com/dfinity/motoko/pull/5281/files#diff-95f6b3b28a82d084ba1f943362b8c74c7e767c290599ca8e44d4ca276acc8763) file. The other changes (compared with master) are due to an unrelated issue. I'll change the target of the branch to the branch related to that fix to limit the number of changes files in this PR. **Do not merge**

Fixes #4939

### CODE REVIEW

**Comment by Kamirus** [comment]
> hi bro, after clone this repo, and run `sudo nix --extra-experimental-features 'nix-command flakes' develop i got
> 
> ```batchfile
> error: input 'https://github.com/viperproject/viperserver/releases/download/v.22.11-release/viperserver.jar' is unsupported`
> ```
> 
> how can i fix it？

Sorry for late reply I was on vacation. [Here is the link how to do the setup](https://github.com/dfinity/motoko/blob/master/Building.md#nix-setup). Did you followed it and still encountered this issue?

File: src/wasm-exts/customModuleEncode.ml [hunk 1]
```diff
@@ -760,13 +760,21 @@ let encode (em : extended_module) =
 
     let (here_dir, asset_dir) = (0, 1) (* reversed indices in dir_names, below *)
     let source_names =
-      ref [ "prelude", (Promise.make (), asset_dir)
-          ; "prim", (Promise.make (), asset_dir)
-          ; "rts.wasm", (Promise.make (), asset_dir) ] (* make these appear last in .debug_line file_name_entries *)
+      [ "prelude", (Promise.make (), asset_dir)
+      ; "prim", (Promise.make (), asset_dir)
```
Comment (crusso) [inline src/wasm-exts/customModuleEncode.ml:764]:
```suggestion
      ; "prim", (Promise.make (), asset_dir) 
      ; "internals", (Promise.make (), asset_dir) 
      ; "timers-api",  (Promise.make (), asset_dir) 
```
I think there's two more that can appear. Does it harm to include them if unused?

File: src/wasm-exts/customModuleEncode.ml [hunk 2]
```diff
@@ -760,13 +760,21 @@ let encode (em : extended_module) =
...
+      ; "rts.wasm", (Promise.make (), asset_dir) ] (* make these appear last in .debug_line file_name_entries *)
```
Comment (crusso) [inline src/wasm-exts/customModuleEncode.ml:767]: I wonder if the name of the rts actually depends in the flavour or not (debug etc).

Comment (crusso) [reply src/wasm-exts/customModuleEncode.ml:767]: Actually, I think rts.wasm is probably the same for all flavours. See pipeline.ml.

File: src/wasm-exts/customModuleEncode.ml (hunk 1 above)
Comment (crusso) [reply src/wasm-exts/customModuleEncode.ml:764]: (See files in src/prelude/prelude.ml, IIRC)

Comment (Kamirus) [reply src/wasm-exts/customModuleEncode.ml:764]: ~Oh maybe that is why `internals.mo` where missing during debugging~
EDIT: `internals` where wrongly added to the `here_dir` instead of `asset_dir`. Debugger can be later updated to use `<moc-asset>` instead of `.`

**Comment by hapeeeeee** [comment]
Could you share a precompiled `moc` binary (x86\_64-linux) in which the “file index too high” issue has already been fixed?
I’d like to use it to check whether the “file index: out of bound” problem mentioned in [https://github.com/scalebit/motoko\_debugger/issues/4](https://github.com/scalebit/motoko_debugger/issues/4) still exists.

Or, if you have already tested it, are there any other issues remaining?

**Comment by Kamirus** [comment]
I've tested it and updated my findings in https://github.com/dfinity/motoko-core/pull/327.
Together with the fix to `moc` (this PR) and the resolved `File not found` I think the debugger works pretty well!

**Review by crusso — APPROVED** [review]
Looks ok to me. I guess it would be slightly better if this list was populated from the code generators, and not here, but it's fine.
