### PR TITLE
fix: don't miss `type` fields in pattern match

### LINKED ISSUE #5825: Sometimes I cannot import a `type` field
While debugging #5824, I found this obviously strange behaviour

```Motoko
> let { type C } : module { type A = Int; type B = Int; type C = Int } =
  module { public type A = Int; public type B = Int; public type C = Int; public type D = Int };
```

I get this error with v1.1.0:
```
stdin:1.7-1.13: type error [M0119], object type field C is not contained in expected type
  module {type A = Int; type B = Int; type C = Int}
```
The error message even says that there is `type C = Int` in the actor type!

I have a fix.

### PR DESCRIPTION
**Pull request by ggreif**
find `type` fields in imports, even when not alphabetically aligned

The problem was that `Lib.List.align` only works for both input lists sorted and when passed the (in spirit) same comparison as for sorting. This was not the case here, the comparison was flipped.

Fixes #5825.

Candidate for bugfix release.

### CODE REVIEW

File: src/mo_frontend/typing.ml [hunk 1]
```diff
@@ -3548,8 +3544,8 @@ and check_pat_fields_typ_dec env t fs tfs pfs te at : Scope.typ_env =
   (* Assumes fs, tfs, and pfs are sorted *)
   let typ_pfs, val_pfs = List.partition_map (fun pf -> match pf.it with
     | ValPF(id, p) -> Either.Right(id, p)
-    | TypPF(id) -> Either.Left(id, pf.at)) pfs in
-  let cmp = fun tf (id, _) -> String.compare id.it tf.T.lab in
+    | TypPF id -> Either.Left(id, pf.at)) pfs in
+  let cmp tf (id, _) = String.compare tf.T.lab id.it in
```
Comment (ggreif) [inline src/mo_frontend/typing.ml:3560]: This is the fix. The `compare` arguments were flipped. See other places where a `cmp` is passed to `Lib.List.align`.

File: test/run/import-type-field.mo [hunk 2]
```diff
@@ -1 +1,5 @@
 import { type List; cons } = "lib/ListM";
+
+
```
Comment (ggreif) [inline test/run/import-type-field.mo]:
```suggestion

```

**Review by christoph-dfinity — APPROVED** [review]
Whoops... Good catch. Thank you for fixing.
