### PR TITLE
fix: record update should type-check like record creation

### LINKED ISSUE #5628: Improve type inference upon record update
(As already discussed with Kamil)
Type inference on record update is not as strong as on record creation:
```
  public shared ({ caller }) func addWorkout(id : Text, exercises : [Exercise], duration : Nat) : async () {
    let workout : Workout = {
      exercises = Map.fromIter(exercises.enumerate()); //here NO explicit type annotation (<Nat,Exercise>) necessary
      duration;
      timestamp = Time.now();
    };
    workouts.add(id, workout);
  };
```
vs. 
```
  public shared ({ caller }) func updateWorkout(id : Text, exercises : [Exercise], duration : Nat) : async () {
    let existingWorkout = getWorkoutInternal(id);
    let updatedWorkout : Workout = {
      existingWorkout with
      exercises = Map.fromIter<Nat,Exercise>(exercises.enumerate()); //here explicit type annotation (<Nat,Exercise>) necessary
      duration;
    };
    workouts.add(id, updatedWorkout);
  };
```

Would be great to also make this implicit typing consistent for both cases. 
Thank you!

### PR DESCRIPTION
**Pull request by Kamirus**
Improve type inference for record update syntax. Example
```motoko
let w : Workout = {
  workout with
  exercises = Map.empty(); // should typecheck without type instantiation
  duration;
};
```
fixes #5628

### CODE REVIEW

File: src/mo_frontend/typing.ml [hunk 1]
```diff
@@ -2237,7 +2237,7 @@ and infer_check_bases_fields env (check_fields : T.field list) exp_at exp_bases
 
   let infer_or_check rf =
     let { mut; id; exp } = rf.it in
-    match List.find_opt (fun ft -> ft.T.lab = id.it) check_fields with
+    match List.find_opt T.(fun ft -> ft.lab = id.it && not (is_typ ft.typ)) check_fields with
```
Comment (Kamirus) [inline src/mo_frontend/typing.ml]: The `rf` are always value-level, yes? So we need to skip the `type <id> = <typ>` fields.
`normalize` not necessary, right?

File: src/mo_frontend/typing.ml [hunk 2]
```diff
@@ -729,6 +729,10 @@ let infer_class_cap env obj_sort (tbs : T.bind list) cs =
   | _ ->
     C.NullCap, tbs, cs
 
+let find_field (ef : exp_field) (fts : T.field list) = 
+  let id = ef.it.id.it in
+  List.find_opt T.(fun ft -> ft.lab = id && not (is_typ ft.typ)) fts
```
Comment (Kamirus) [inline src/mo_frontend/typing.ml]: `exp_field` is always value-level, yes? So we need to skip the `type <id> = <typ>` T.fields.
`normalize` not necessary, right?

File: src/mo_frontend/typing.ml [hunk 3]
```diff
@@ -2411,22 +2414,24 @@ and check_exp' env0 t exp : T.typ =
...
+      |> List.map (fun ft -> Printf.sprintf "'%s'" ft.T.lab)
+    in
+    begin match missing_field_labs with
+    | [] -> check_inferred env0 env t t' exp
+    | fts ->
+      (* Future work: Replace this error with a general subtyping error once better explanations are available. *)
+      let s = if List.length fts = 1 then "" else "s" in
+      local_error env exp.at "M0151" "missing field%s %s from expected type%a" s (String.concat ", " fts) display_typ_expand t;
+      t'
+    end
```
Comment (Kamirus) [inline src/mo_frontend/typing.ml]: All of this should be redundant (replaced with just `check_inferred env0 env t t' exp`) once we have time to complete https://github.com/dfinity/motoko/pull/5409

File: src/mo_frontend/typing.ml (hunk 2 above)
Comment (crusso) [reply src/mo_frontend/typing.ml]: Normalize should not be necessary to distinguish a type field from a value field, no. Ditto for T.mut

Comment (crusso) [reply src/mo_frontend/typing.ml]: There should be a Type.find_val_field_opt or similar that does this for I think.

File: src/mo_frontend/typing.ml [hunk 4]
```diff
@@ -2411,22 +2414,24 @@ and check_exp' env0 t exp : T.typ =
...
-    then detect_lost_fields env t e;
-    t
+  | ObjE (exp_bases, exp_fields), T.Obj(T.Object, fts) ->
+    let t' = infer_check_bases_fields env fts exp.at exp_bases exp_fields in
+    let fts' = match T.promote t' with
+      | T.Obj(T.Object, fts') -> fts'
+      | _ -> []
+    in
+    let missing_field_labs =
+      List.filter (fun ft -> not (List.exists (fun ft' -> ft.T.lab = ft'.T.lab) fts')) fts
```
Comment (crusso) [inline src/mo_frontend/typing.ml]: I wonder if this should be distinguishing type fields from value fields. They can have the same name. Maybe this was a lurking bug?

File: src/mo_frontend/typing.ml [hunk 5]
```diff
@@ -2411,22 +2414,24 @@ and check_exp' env0 t exp : T.typ =
   | TupE exps, T.Tup ts when List.length exps = List.length ts ->
     List.iter2 (check_exp env) ts exps;
     t
-  | ObjE ([], exp_fields) as e, T.Obj(T.Object, fts) -> (* TODO: infer bases? Default does a decent job. *)
-    check_ids env "object" "field"
```
Comment (crusso) [inline src/mo_frontend/typing.ml:2415]: Has this check (check_ids) been removed? I think it checks the field names are distinct and needs to be done somewhere.

Comment (Kamirus) [reply src/mo_frontend/typing.ml:2415]: It is still there, in the `infer_check_bases_fields`

File: src/mo_frontend/typing.ml (hunk 4 above)
Comment (Kamirus) [reply src/mo_frontend/typing.ml]: Yes, another limitation of this extra check is that it is not checking whether the type matches.
Anyway, if this check does not catch the error, the `check_inferred` will. This is just an extra check.
But yeah I'll change to only val fields

File: src/mo_frontend/typing.ml (hunk 2 above)
Comment (Kamirus) [reply src/mo_frontend/typing.ml]: Thanks! `lookup_val_field_opt` is there, but it returns the type instead of the full field, but I've moved the `find_val_field_opt` next to that

File: src/mo_frontend/typing.ml (hunk 5 above)
Comment (ggreif) [reply src/mo_frontend/typing.ml:2415]: So basically the whole infrastructure was there already, just had to be glued in?

File: src/mo_frontend/typing.ml [hunk 6]
```diff
@@ -2411,22 +2411,24 @@ and check_exp' env0 t exp : T.typ =
   | TupE exps, T.Tup ts when List.length exps = List.length ts ->
     List.iter2 (check_exp env) ts exps;
     t
-  | ObjE ([], exp_fields) as e, T.Obj(T.Object, fts) -> (* TODO: infer bases? Default does a decent job. *)
```
Comment (ggreif) [inline src/mo_frontend/typing.ml:2414]: Yeah, I remember punting on this back then. Good that Caffeine made an opening!

File: test/run/record-update-inference.mo [hunk 7]
```diff
@@ -0,0 +1,62 @@
+// Issue #418: type inference on record update should be as strong as on record creation
```
Comment (ggreif) [inline test/run/record-update-inference.mo]: Did he migrate the issue? Please correct the number!

**Review by ggreif — APPROVED** [review]
Looks solid to me. I think this can go in as soon as @crusso's comments are addressed!

Thanks for filling in the gaping hole I left behind!
